name: sync code

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up temporary build directory
      run: |
        mkdir -p ./build
        rsync -av --exclude='.git/' --exclude='.github/' --exclude='.gitignore' --exclude='.gitattributes' ./ ./build/

    - name: Upload to WebDAV
      uses: bxb100/action-upload@main
      with:
        provider: webdav
        provider_options: |
          endpoint=${{ secrets.WEBDAV_ENDPOINT }}
          username=${{ secrets.WEBDAV_USERNAME }}
          password=${{ secrets.WEBDAV_PASSWORD }}
          root=${{ secrets.WEBDAV_ROOT }}
        include: './build/**'